version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: direktvermarktet-dev-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: dev
      MYSQL_PASSWORD: devpassword
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql
