services:
  mysql:
    image: mysql:8.0
    container_name: direktvermarktet-dev-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
